package theme

// The `theme` command: the switcher's CLI and its live-reload side effects.
//
// Reached either as `setup theme <args>` or, more usually, through the `theme`
// symlink next to the binary — main() dispatches on argv[0].

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/jrdriscoll17/hydra/internal/recolor"
	"github.com/jrdriscoll17/hydra/internal/sys"
)

const themeUsage = `Global theme switcher.

One palette per theme lives in themes/<name>.json. Everything else on this
box is generated from it, so a theme is defined in exactly one place:

    theme list          # show the themes and which one is live
    theme icons         # rebuild the icon index (after installing apps)
    theme recolor <base> <#hex> <name>   # a Material-Black set in any colour
    theme set <name>    # switch to it
    theme apply         # re-render the current theme (run at Hyprland start)
    theme next          # cycle

Generated files carry a "GENERATED by ~/.config/theme" header. Editing them
directly is pointless — the next switch overwrites them. Edit the JSON, then
` + "`theme apply`" + `.`

var listactiveRe = regexp.MustCompile(`(?m)^\S+: (/.*)$`)

// setWallpaper points every output at path, and makes sure it actually took.
//
// This hyprpaper build (0.8.4) only accepts `wallpaper` and `listactive` —
// `preload`, `unload` and `reload` all answer "invalid hyprpaper request". So an
// image that isn't already in memory can't be preloaded: the first `wallpaper`
// request kicks off an async load, returns success, and leaves the old wallpaper
// up. That's what made a theme switch appear to need doing twice. Re-issue until
// listactive agrees, which costs one extra call once the image is warm.
func setWallpaper(path string) bool {
	// hyprpaper reports the canonical path in `listactive`, and the wallpaper
	// dir is a symlink (~/.config/hypr/wallpapers -> the wallpapers repo), so
	// compare resolved paths — a literal match never succeeds through a link.
	expected, err := filepath.EvalSymlinks(path)
	if err != nil {
		expected = path
	}

	for attempt := range 24 {
		// Re-issue only at the start and once more if it's clearly stuck: each
		// request makes hyprpaper decode the image again, which is what made a
		// switch spin the fans.
		if attempt == 0 || attempt == 12 {
			sys.Quiet("hyprctl", "hyprpaper", "wallpaper", ","+path)
		}

		active, _ := sys.Quiet("hyprctl", "hyprpaper", "listactive")
		// Lines look like "DP-1: /path/to.jpg"; hyprctl's own diagnostics
		// ("error: can't send: ...") also contain a colon, so match the shape.
		matches := listactiveRe.FindAllStringSubmatch(active, -1)

		if len(matches) > 0 {
			all := true
			for _, m := range matches {
				got, err := filepath.EvalSymlinks(strings.TrimSpace(m[1]))
				if err != nil {
					got = strings.TrimSpace(m[1])
				}
				if got != expected {
					all = false
					break
				}
			}
			if all {
				return true
			}
		} else {
			// No monitors listed at all means hyprpaper isn't up — it starts
			// alongside `theme apply` at login. It reads the generated
			// hyprpaper.conf when it does come up, so there is nothing to retry.
			return false
		}

		// Decoding a 4K JPEG takes a moment; poll rather than nag.
		time.Sleep(100 * time.Millisecond)
	}

	fmt.Fprintf(os.Stderr, "theme: hyprpaper did not switch to %s\n", filepath.Base(path))
	return false
}

func reloadAll(t *Theme) {
	// Hyprland window borders. hyprland.lua does not read the palette, so these
	// are pushed live and re-pushed from autostart via `theme apply`.
	//
	// `hyprctl keyword` is refused outright by a Lua config ("keyword can't work
	// with non-legacy parsers"); `eval` runs a string against the same hl API
	// the config uses.
	sys.Quiet("hyprctl", "eval", fmt.Sprintf(
		"hl.config({ general = { col = { active_border = %q, inactive_border = %q } } })",
		rgbaColor(t.c("accent"), 0.93), rgbaColor(t.c("base"), 0.67)))

	setWallpaper(t.wallpaperPath())

	// Notifications are drawn by the shell now, so there is no daemon to
	// reload: the cards read Theme.* and follow the hot-reloaded palette.
	//
	// kitty reloads its config on SIGUSR1; alacritty and quickshell watch their
	// own files, so they need nothing.
	sys.Quiet("pkill", "-USR1", "-x", "kitty")

	// GTK4/libadwaita and anything using the settings portal read gsettings,
	// not settings.ini.
	// Cursor theme is deliberately absent: it isn't part of any of these
	// palettes, and switching themes shouldn't change the pointer.
	for _, kv := range [][2]string{
		{"gtk-theme", t.GTK.Theme},
		{"icon-theme", t.GTK.Icons},
		{"color-scheme", "prefer-dark"},
	} {
		sys.Quiet("gsettings", "set", "org.gnome.desktop.interface", kv[0], kv[1])
	}
}

func Apply(name string, quiet bool) error {
	t, err := Load(name)
	if err != nil {
		return err
	}
	for _, r := range renderers {
		if err := r.fn(t); err != nil {
			return fmt.Errorf("%s: %w", r.name, err)
		}
	}
	if err := sys.WriteFile(stateFile(), name+"\n"); err != nil {
		return err
	}
	reloadAll(t)
	if !quiet {
		fmt.Printf("theme: %s\n", t.Label)
	}
	return nil
}

func cmdList() error {
	live := Current()
	names, err := Names()
	if err != nil {
		return err
	}
	for _, name := range names {
		t, err := Load(name)
		if err != nil {
			return err
		}
		mark := " "
		if name == live {
			mark = "*"
		}
		fmt.Printf(" %s %-10s %-12s %s\n", mark, name, t.Label, t.Blurb)
	}
	return nil
}

// cmdData is everything the Quickshell picker needs, in one read.
func cmdData() error {
	names, err := Names()
	if err != nil {
		return err
	}

	type entry struct {
		Name      string            `json:"name"`
		Label     string            `json:"label"`
		Blurb     string            `json:"blurb"`
		Colors    map[string]string `json:"colors"`
		Wallpaper string            `json:"wallpaper"`
	}
	payload := struct {
		Current string  `json:"current"`
		Themes  []entry `json:"themes"`
	}{Current: Current()}

	for _, n := range names {
		t, err := Load(n)
		if err != nil {
			return err
		}
		colors := map[string]string{}
		for _, k := range t.Colors.Keys() {
			colors[k] = t.c(k)
		}
		payload.Themes = append(payload.Themes, entry{
			Name: t.Name, Label: t.Label, Blurb: t.Blurb,
			Colors: colors, Wallpaper: t.wallpaperPath(),
		})
	}

	out, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	fmt.Println(string(out))
	return nil
}

// cmdIcons forces the icon index to be rebuilt — after installing new apps or
// changing the icon theme by hand.
func cmdIcons() error {
	os.Remove(sys.InHome(".config/quickshell/generated/icons.theme"))
	if entries, err := os.ReadDir(cacheDir()); err == nil {
		for _, e := range entries {
			if strings.HasPrefix(e.Name(), "icons-") && strings.HasSuffix(e.Name(), ".json") {
				os.Remove(filepath.Join(cacheDir(), e.Name()))
			}
		}
	}
	return Apply(Current(), false)
}

// ThemeMain is the `theme` CLI.
func Main(argv []string) error {
	cmd := "list"
	if len(argv) > 0 {
		cmd = argv[0]
	}

	names, _ := Names()

	switch cmd {
	case "list", "-l", "--list":
		return cmdList()
	case "data":
		return cmdData()
	case "recolor":
		if len(argv) != 4 {
			return fmt.Errorf("recolor: need <base> <#hex> <name>")
		}
		return recolor.Run(argv[1], argv[2], argv[3])
	case "icons":
		return cmdIcons()
	case "current":
		fmt.Println(Current())
		return nil
	case "apply":
		return Apply(Current(), slicesContains(argv, "--quiet"))
	case "next":
		if len(names) == 0 {
			return fmt.Errorf("no themes installed")
		}
		live := Current()
		idx := 0
		for i, n := range names {
			if n == live {
				idx = i
				break
			}
		}
		return Apply(names[(idx+1)%len(names)], false)
	case "set", "-s":
		if len(argv) < 2 {
			return fmt.Errorf("set: need a theme name")
		}
		return Apply(argv[1], false)
	case "-h", "--help", "help":
		fmt.Println(themeUsage)
		return nil
	default:
		if slicesContains(names, cmd) {
			return Apply(cmd, false)
		}
		return fmt.Errorf("unknown command: %s\ntry: theme list", cmd)
	}
}
