package theme

// Palette loading for the theme switcher.
//
// The colours are an *ordered* map: render_quickshell and render_nvim emit one
// line per colour in the order the JSON declares them, so a plain Go map would
// scramble both files on every run.

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/jrdriscoll17/hydra/internal/sys"
)

const bannerFmt = "GENERATED by ~/.config/theme — edit themes/%s.json and run `theme apply`."

var (
	themeRoot   = func() string { return sys.InHome(".config/theme") }
	themesDir   = func() string { return sys.InHome(".config/theme/themes") }
	stateFile   = func() string { return sys.InHome(".config/theme/current") }
	wallpaperer = func() string { return sys.InHome(".config/hypr/wallpapers") }
	cacheDir    = func() string { return sys.InHome(".cache/theme") }
)

// Ordered is a string map that remembers its JSON key order.
type Ordered struct {
	keys   []string
	values map[string]string
}

// Nil-safe: a theme built by hand, or one whose JSON simply omits "colors",
// leaves the field nil, and asking such a palette for a colour should answer
// "it has not got one" rather than panic.
func (o *Ordered) Get(k string) string {
	if o == nil {
		return ""
	}
	return o.values[k]
}

func (o *Ordered) Keys() []string {
	if o == nil {
		return nil
	}
	return o.keys
}

// UnmarshalJSON reads the object as a token stream so key order survives.
func (o *Ordered) UnmarshalJSON(data []byte) error {
	o.keys = nil
	o.values = map[string]string{}

	dec := json.NewDecoder(strings.NewReader(string(data)))
	tok, err := dec.Token()
	if err != nil {
		return err
	}
	if d, ok := tok.(json.Delim); !ok || d != '{' {
		return fmt.Errorf("expected a JSON object, got %v", tok)
	}
	for dec.More() {
		keyTok, err := dec.Token()
		if err != nil {
			return err
		}
		key, ok := keyTok.(string)
		if !ok {
			return fmt.Errorf("expected a string key, got %v", keyTok)
		}
		var value string
		if err := dec.Decode(&value); err != nil {
			return err
		}
		if _, seen := o.values[key]; !seen {
			o.keys = append(o.keys, key)
		}
		o.values[key] = value
	}
	_, err = dec.Token() // closing brace
	return err
}

// Theme is one palette file.
type Theme struct {
	Name      string   `json:"name"`
	Label     string   `json:"label"`
	Blurb     string   `json:"blurb"`
	Wallpaper string   `json:"wallpaper"`
	Colors    *Ordered `json:"colors"`
	Term      *Ordered `json:"term"`
	GTK       struct {
		Theme   string `json:"theme"`
		Icons   string `json:"icons"`
		Kvantum string `json:"kvantum"`
		GTK4    string `json:"gtk4"`
	} `json:"gtk"`
	Editors struct {
		Doom string `json:"doom"`
		Nvim string `json:"nvim"`
	} `json:"editors"`

	banner string
}

// Color looks up one palette colour by name.
func (t *Theme) Color(key string) string { return t.Colors.Get(key) }

func (t *Theme) c(key string) string    { return t.Color(key) }
func (t *Theme) term(key string) string { return t.Term.Get(key) }

// wallpaperPath is the absolute path the renderers and hyprpaper both use.
func (t *Theme) wallpaperPath() string {
	return filepath.Join(wallpaperer(), t.Wallpaper)
}

func Load(name string) (*Theme, error) {
	path := filepath.Join(themesDir(), name+".json")
	raw, err := os.ReadFile(path)
	if err != nil {
		all, _ := Names()
		return nil, fmt.Errorf("no such theme: %s\navailable: %s",
			name, strings.Join(all, ", "))
	}
	var t Theme
	if err := json.Unmarshal(raw, &t); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	t.banner = fmt.Sprintf(bannerFmt, name)
	return &t, nil
}

// themeNames lists the palettes, sorted, matching Python's sorted(glob).
func Names() ([]string, error) {
	entries, err := os.ReadDir(themesDir())
	if err != nil {
		return nil, err
	}
	var names []string
	for _, e := range entries {
		if before, ok := strings.CutSuffix(e.Name(), ".json"); ok {
			names = append(names, before)
		}
	}
	sort.Strings(names)
	return names, nil
}

// currentTheme falls back to the first palette when the state file is absent or
// names something that no longer exists.
func Current() string {
	names, err := Names()
	if err != nil || len(names) == 0 {
		return ""
	}
	if raw, err := os.ReadFile(stateFile()); err == nil {
		name := strings.TrimSpace(string(raw))
		if slices.Contains(names, name) {
			return name
		}
	}
	return names[0]
}
