package theme

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The renderers write files other programs parse, and several of them are
// diffed against the config repo, so the contract is the exact bytes rather
// than "contains the right colours". These goldens are that contract: a diff
// here means a generated config changed shape, which is worth a deliberate
// look before `-update` blesses it.
var update = flag.Bool("update", false, "rewrite the golden files in testdata")

func golden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("testdata", name+".golden")

	if *update {
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}

	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading golden %s: %v\n(run `go test ./internal/theme -update` to create it)", path, err)
	}
	if want := string(raw); got != want {
		t.Errorf("%s does not match its golden file.\n--- got ---\n%s\n--- want ---\n%s", name, got, want)
	}
}

// renderTo runs one renderer against the fixture palette in a temp HOME and
// returns the file it wrote.
func renderTo(t *testing.T, fn func(*Theme) error, out string) string {
	t.Helper()
	home := fixtureHome(t)
	th := loadFixture(t)
	if err := fn(th); err != nil {
		t.Fatalf("render: %v", err)
	}
	return readFile(t, filepath.Join(home, out))
}

func TestRenderQuickshell(t *testing.T) {
	got := renderTo(t, renderQuickshell, ".config/quickshell/generated/Colors.qml")
	golden(t, "Colors.qml", got)

	// The property list must follow the palette's own order, since that is the
	// only thing keeping this file stable between runs.
	first := strings.Index(got, "property color base:")
	last := strings.Index(got, "property color accent:")
	if first < 0 || last < 0 || first > last {
		t.Error("colour properties are not emitted in palette order")
	}
}

func TestRenderKitty(t *testing.T) {
	golden(t, "kitty-theme.conf", renderTo(t, renderKitty, ".config/kitty/theme.conf"))
}

func TestRenderAlacritty(t *testing.T) {
	got := renderTo(t, renderAlacritty, ".config/alacritty/colors.toml")
	golden(t, "alacritty-colors.toml", got)

	// alacritty wants '0xRRGGBB', not '#RRGGBB'.
	if strings.Contains(got, "'#") {
		t.Error("colours are emitted with a leading #; alacritty expects 0x")
	}
}

func TestRenderNvim(t *testing.T) {
	golden(t, "nvim-theme.lua", renderTo(t, renderNvim, ".config/nvim/lua/theme.lua"))
}

func TestRenderDoom(t *testing.T) {
	golden(t, "doom-theme.el", renderTo(t, renderDoom, ".config/doom/theme.el"))
}

func TestRenderBtopTheme(t *testing.T) {
	golden(t, "btop-fixture.theme", renderTo(t, renderBtop, ".config/btop/themes/fixture.theme"))
}

func TestRenderHypr(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)
	if err := renderHypr(th); err != nil {
		t.Fatalf("renderHypr: %v", err)
	}

	// The wallpaper path is absolute and so varies by temp dir; normalise it so
	// the golden stays stable.
	norm := func(s string) string { return strings.ReplaceAll(s, home, "$HOME") }
	golden(t, "hyprpaper.conf", norm(readFile(t, filepath.Join(home, ".config/hypr/hyprpaper.conf"))))
	golden(t, "hypr-colors.conf", norm(readFile(t, filepath.Join(home, ".config/hypr/colors.conf"))))
}

// Every generated file carries the header, which is what stops someone editing
// the output instead of the palette.
func TestRenderersEmitTheGeneratedBanner(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	cases := []struct {
		name string
		fn   func(*Theme) error
		out  string
	}{
		{"quickshell", renderQuickshell, ".config/quickshell/generated/Colors.qml"},
		{"kitty", renderKitty, ".config/kitty/theme.conf"},
		{"alacritty", renderAlacritty, ".config/alacritty/colors.toml"},
		{"nvim", renderNvim, ".config/nvim/lua/theme.lua"},
		{"doom", renderDoom, ".config/doom/theme.el"},
		{"btop", renderBtop, ".config/btop/themes/fixture.theme"},
		{"hyprpaper", renderHypr, ".config/hypr/hyprpaper.conf"},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if err := c.fn(th); err != nil {
				t.Fatalf("render: %v", err)
			}
			got := readFile(t, filepath.Join(home, c.out))
			if !strings.Contains(got, "GENERATED by ~/.config/theme") {
				t.Errorf("no GENERATED banner in %s", c.out)
			}
		})
	}
}

// Rendering twice must produce identical bytes — the switcher runs on every
// Hyprland start, and chezmoi diffs several of these files.
func TestRenderersAreDeterministic(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	outputs := []string{
		".config/quickshell/generated/Colors.qml",
		".config/kitty/theme.conf",
		".config/alacritty/colors.toml",
		".config/nvim/lua/theme.lua",
		".config/doom/theme.el",
		".config/btop/themes/fixture.theme",
		".config/hypr/hyprpaper.conf",
		".config/hypr/colors.conf",
	}
	render := func() map[string]string {
		for _, r := range []func(*Theme) error{
			renderQuickshell, renderKitty, renderAlacritty, renderNvim,
			renderDoom, renderBtop, renderHypr,
		} {
			if err := r(th); err != nil {
				t.Fatalf("render: %v", err)
			}
		}
		out := map[string]string{}
		for _, o := range outputs {
			out[o] = readFile(t, filepath.Join(home, o))
		}
		return out
	}

	first := render()
	for range 3 {
		for path, content := range render() {
			if content != first[path] {
				t.Errorf("%s changed between renders of the same palette", path)
			}
		}
	}
}

// -- btop --------------------------------------------------------------------

// The theme file is generated whole, but btop.conf belongs to btop and is only
// retargeted — hand-made settings in it have to survive.
func TestRenderBtopRetargetsConfWithoutTouchingTheRest(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	writeFile(t, filepath.Join(home, ".config/btop/btop.conf"), strings.Join([]string{
		`#? Config file for btop`,
		`color_theme = "/some/old/theme.theme"`,
		`theme_background = False`,
		`update_ms = 2000`,
		``,
	}, "\n"))

	if err := renderBtop(th); err != nil {
		t.Fatalf("renderBtop: %v", err)
	}

	got := readFile(t, filepath.Join(home, ".config/btop/btop.conf"))
	want := `color_theme = "` + home + `/.config/btop/themes/fixture.theme"`
	if !strings.Contains(got, want) {
		t.Errorf("color_theme not retargeted:\n%s", got)
	}
	for _, keep := range []string{"theme_background = False", "update_ms = 2000", "#? Config file for btop"} {
		if !strings.Contains(got, keep) {
			t.Errorf("btop.conf lost %q:\n%s", keep, got)
		}
	}
}

func TestRenderBtopWithNoConfFile(t *testing.T) {
	fixtureHome(t)
	th := loadFixture(t)
	// subLine no-ops on a missing file; the theme file is still written.
	if err := renderBtop(th); err != nil {
		t.Errorf("renderBtop with no btop.conf returned %v, want nil", err)
	}
}

// -- GTK ---------------------------------------------------------------------

func TestRenderGTKSettingsINI(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	if err := renderGTK(th); err != nil {
		t.Fatalf("renderGTK: %v", err)
	}

	for _, v := range []string{"gtk-3.0", "gtk-4.0"} {
		got := readFile(t, filepath.Join(home, ".config", v, "settings.ini"))
		for _, want := range []string{
			"[Settings]",
			"gtk-theme-name=Material-Black-Fixture",
			"gtk-icon-theme-name=MB-Fixture-Suru-GLOW",
			"gtk-application-prefer-dark-theme=1",
		} {
			if !strings.Contains(got, want) {
				t.Errorf("%s/settings.ini missing %q:\n%s", v, want, got)
			}
		}
	}
}

// nwg-look owns the header and the .gtkrc-2.0.mine include; only the two theme
// lines may be retargeted.
func TestRenderGTKEditsExistingGtkrc2(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	writeFile(t, filepath.Join(home, ".gtkrc-2.0"), strings.Join([]string{
		`# Generated by nwg-look`,
		`gtk-theme-name="Old-Theme"`,
		`gtk-icon-theme-name="Old-Icons"`,
		`gtk-font-name="Ubuntu Nerd Font 11"`,
		`include "/home/jake/.gtkrc-2.0.mine"`,
		``,
	}, "\n"))

	if err := renderGTK(th); err != nil {
		t.Fatalf("renderGTK: %v", err)
	}

	got := readFile(t, filepath.Join(home, ".gtkrc-2.0"))
	for _, want := range []string{
		`gtk-theme-name="Material-Black-Fixture"`,
		`gtk-icon-theme-name="MB-Fixture-Suru-GLOW"`,
		`# Generated by nwg-look`,
		`gtk-font-name="Ubuntu Nerd Font 11"`,
		`include "/home/jake/.gtkrc-2.0.mine"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf(".gtkrc-2.0 missing %q:\n%s", want, got)
		}
	}
	if strings.Contains(got, "Old-Theme") || strings.Contains(got, "Old-Icons") {
		t.Errorf(".gtkrc-2.0 kept the previous theme:\n%s", got)
	}
}

func TestRenderGTKCreatesGtkrc2WhenAbsent(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	if err := renderGTK(th); err != nil {
		t.Fatalf("renderGTK: %v", err)
	}
	got := readFile(t, filepath.Join(home, ".gtkrc-2.0"))
	for _, want := range []string{
		`gtk-theme-name="Material-Black-Fixture"`,
		`gtk-icon-theme-name="MB-Fixture-Suru-GLOW"`,
		`gtk-font-name="Ubuntu Nerd Font 11"`,
	} {
		if !strings.Contains(got, want) {
			t.Errorf("generated .gtkrc-2.0 missing %q:\n%s", want, got)
		}
	}
}

// libadwaita apps ignore the theme name and read ~/.config/gtk-4.0/gtk.css, so
// the switcher symlinks it out of whichever theme the palette names for gtk4.
func TestRenderGTKLinksGTK4Sheets(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	src := filepath.Join(home, ".themes", "Colloid-Teal-Dark-Nord", "gtk-4.0")
	writeFile(t, filepath.Join(src, "gtk.css"), "/* gtk4 */")
	writeFile(t, filepath.Join(src, "gtk-dark.css"), "/* gtk4 dark */")

	if err := renderGTK(th); err != nil {
		t.Fatalf("renderGTK: %v", err)
	}

	for _, css := range []string{"gtk.css", "gtk-dark.css"} {
		link := filepath.Join(home, ".config/gtk-4.0", css)
		target, err := os.Readlink(link)
		if err != nil {
			t.Errorf("%s is not a symlink: %v", css, err)
			continue
		}
		if want := filepath.Join(src, css); target != want {
			t.Errorf("%s -> %q, want %q", css, target, want)
		}
	}
}

func TestRenderGTKReplacesAStaleGTK4Link(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	src := filepath.Join(home, ".themes", "Colloid-Teal-Dark-Nord", "gtk-4.0")
	writeFile(t, filepath.Join(src, "gtk.css"), "/* gtk4 */")

	// A link left behind by the previous theme.
	stale := filepath.Join(home, ".config/gtk-4.0", "gtk.css")
	mkdir(t, filepath.Dir(stale))
	if err := os.Symlink(filepath.Join(home, ".themes/Old/gtk-4.0/gtk.css"), stale); err != nil {
		t.Fatal(err)
	}

	if err := renderGTK(th); err != nil {
		t.Fatalf("renderGTK: %v", err)
	}
	target, err := os.Readlink(stale)
	if err != nil {
		t.Fatalf("gtk.css is not a symlink: %v", err)
	}
	if want := filepath.Join(src, "gtk.css"); target != want {
		t.Errorf("stale link not replaced: -> %q, want %q", target, want)
	}
}

// A missing gtk4 theme must leave no link at all rather than a dangling one,
// which GTK4 would fail to read.
func TestRenderGTKRemovesLinksWhenTheGTK4ThemeIsAbsent(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)

	stale := filepath.Join(home, ".config/gtk-4.0", "gtk.css")
	mkdir(t, filepath.Dir(stale))
	if err := os.Symlink(filepath.Join(home, ".themes/Old/gtk-4.0/gtk.css"), stale); err != nil {
		t.Fatal(err)
	}

	if err := renderGTK(th); err != nil {
		t.Fatalf("renderGTK: %v", err)
	}
	if _, err := os.Lstat(stale); !os.IsNotExist(err) {
		t.Error("a stale gtk4 link survived even though the theme is not installed")
	}
}

func TestRenderGTKFallsBackToTheMainThemeForGTK4(t *testing.T) {
	home := fixtureHome(t)
	th := loadFixture(t)
	th.GTK.GTK4 = "" // palettes may omit it

	src := filepath.Join(home, ".themes", "Material-Black-Fixture", "gtk-4.0")
	writeFile(t, filepath.Join(src, "gtk.css"), "/* from the main theme */")

	if err := renderGTK(th); err != nil {
		t.Fatalf("renderGTK: %v", err)
	}
	target, err := os.Readlink(filepath.Join(home, ".config/gtk-4.0", "gtk.css"))
	if err != nil {
		t.Fatalf("no gtk.css link: %v", err)
	}
	if want := filepath.Join(src, "gtk.css"); target != want {
		t.Errorf("gtk.css -> %q, want %q", target, want)
	}
}

// -- Qt ----------------------------------------------------------------------

// fakeKvantumBase installs a stock Kvantum theme for renderQt to borrow.
func fakeKvantumBase(t *testing.T) string {
	t.Helper()
	dir := filepath.Join(t.TempDir(), "Nordic-Darker-Solid")
	writeFile(t, filepath.Join(dir, "Nordic-Darker-Solid.kvconfig"), strings.Join([]string{
		`[%General]`,
		`author=Someone`,
		`x11drag=menubar_and_primary_toolbar`,
		``,
		`[GeneralColors]`,
		`window.color=#111111`,
		`base.color=#222222`,
		``,
		`[Hacks]`,
		`transparent_dolphin_view=true`,
		``,
	}, "\n"))
	writeFile(t, filepath.Join(dir, "Nordic-Darker-Solid.svg"), "<svg>widgets</svg>")

	original := kvantumBase
	kvantumBase = dir
	t.Cleanup(func() { kvantumBase = original })
	return dir
}

func TestRenderQt(t *testing.T) {
	home := fixtureHome(t)
	fakeKvantumBase(t)
	th := loadFixture(t)

	if err := renderQt(th); err != nil {
		t.Fatalf("renderQt: %v", err)
	}

	t.Run("the palette gets its own kvconfig", func(t *testing.T) {
		got := readFile(t, filepath.Join(home, ".config/Kvantum/Fixture/Fixture.kvconfig"))
		if !strings.Contains(got, "highlight.color=#111111") {
			t.Errorf("accent not written into GeneralColors:\n%s", got)
		}
		if !strings.Contains(got, "window.color=#010101") {
			t.Errorf("base colour not written:\n%s", got)
		}
		// The rest of the stock theme has to survive: [GeneralColors] is the
		// only block being replaced.
		for _, keep := range []string{"[%General]", "x11drag=menubar_and_primary_toolbar", "[Hacks]"} {
			if !strings.Contains(got, keep) {
				t.Errorf("kvconfig lost %q from the base:\n%s", keep, got)
			}
		}
		if strings.Contains(got, "#222222") {
			t.Errorf("a base GeneralColors value survived:\n%s", got)
		}
	})

	t.Run("the widget SVG is copied", func(t *testing.T) {
		if got := readFile(t, filepath.Join(home, ".config/Kvantum/Fixture/Fixture.svg")); got != "<svg>widgets</svg>" {
			t.Errorf("SVG = %q", got)
		}
	})

	t.Run("kvantum is pointed at the theme", func(t *testing.T) {
		got := readFile(t, filepath.Join(home, ".config/Kvantum/kvantum.kvconfig"))
		if !strings.Contains(got, "theme=Fixture") {
			t.Errorf("kvantum.kvconfig:\n%s", got)
		}
	})

	// This is what gives Qt an icon theme at all, Quickshell included.
	t.Run("qt5ct and qt6ct are configured", func(t *testing.T) {
		for _, qt := range []string{"qt5ct", "qt6ct"} {
			got := readFile(t, filepath.Join(home, ".config", qt, qt+".conf"))
			for _, want := range []string{
				"[Appearance]", "icon_theme=MB-Fixture-Suru-GLOW",
				"style=kvantum", "standard_dialogs=default",
			} {
				if !strings.Contains(got, want) {
					t.Errorf("%s.conf missing %q:\n%s", qt, want, got)
				}
			}
		}
	})
}

// The Kvantum base is an AUR package that may not be installed; the rest of the
// Qt wiring still has to happen.
func TestRenderQtWithoutTheKvantumBase(t *testing.T) {
	home := fixtureHome(t)
	original := kvantumBase
	kvantumBase = filepath.Join(t.TempDir(), "absent")
	t.Cleanup(func() { kvantumBase = original })

	th := loadFixture(t)
	if err := renderQt(th); err != nil {
		t.Fatalf("renderQt with no base returned %v, want nil", err)
	}

	if _, err := os.Stat(filepath.Join(home, ".config/Kvantum/Fixture/Fixture.kvconfig")); !os.IsNotExist(err) {
		t.Error("a kvconfig was written despite the base being absent")
	}
	got := readFile(t, filepath.Join(home, ".config/qt6ct/qt6ct.conf"))
	if !strings.Contains(got, "icon_theme=MB-Fixture-Suru-GLOW") {
		t.Errorf("qt6ct was not configured:\n%s", got)
	}
}

// Existing qt6ct settings the user made by hand must survive a theme switch.
func TestRenderQtPreservesOtherQtSettings(t *testing.T) {
	home := fixtureHome(t)
	fakeKvantumBase(t)
	th := loadFixture(t)

	writeFile(t, filepath.Join(home, ".config/qt6ct/qt6ct.conf"), strings.Join([]string{
		`[Appearance]`,
		`icon_theme=Old-Icons`,
		`style=Fusion`,
		``,
		`[Fonts]`,
		`fixed=@Variant(...)`,
		``,
	}, "\n"))

	if err := renderQt(th); err != nil {
		t.Fatalf("renderQt: %v", err)
	}
	got := readFile(t, filepath.Join(home, ".config/qt6ct/qt6ct.conf"))
	if !strings.Contains(got, "icon_theme=MB-Fixture-Suru-GLOW") || strings.Contains(got, "Old-Icons") {
		t.Errorf("icon_theme not retargeted:\n%s", got)
	}
	if !strings.Contains(got, "[Fonts]") || !strings.Contains(got, "fixed=@Variant(...)") {
		t.Errorf("unrelated settings were lost:\n%s", got)
	}
}

// -- the renderer set --------------------------------------------------------

// renderQuickshell must stay last: writing Colors.qml hot-reloads Quickshell,
// which tears down the QML engine and kills the process the picker spawned.
func TestQuickshellRendersLast(t *testing.T) {
	if len(renderers) == 0 {
		t.Fatal("no renderers registered")
	}
	if got := renderers[len(renderers)-1].name; got != "quickshell" {
		t.Errorf("last renderer is %q, want \"quickshell\" — writing Colors.qml "+
			"hot-reloads the shell and kills this process, so it has to come after "+
			"everything else has landed", got)
	}
}

func TestRendererNamesAreUnique(t *testing.T) {
	seen := map[string]bool{}
	for _, r := range renderers {
		if seen[r.name] {
			t.Errorf("duplicate renderer name %q", r.name)
		}
		seen[r.name] = true
		if r.fn == nil {
			t.Errorf("renderer %q has no function", r.name)
		}
	}
}
